
spring:
  application:
    name: bbs-manager
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: szw123456
    url: 'jdbc:mysql://42.193.114.160:53306/bbs?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8'
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/*.xml

server:
  port: 9192

bbs:
  expireSec: 30000
  secret: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjYwMTQ3MTk3LCJleHAiOjE2NjAxNzcxOTd9.tXA_mvUxjknRo18KfpfggFcnHyK2O95h8xBbrv_cLQ3ieEdPpQp5bcUUqCefLEYDxxjWEoR5nrBeqRfqZJB7Z

