
spring:
  application:
    name: customer-user
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  shardingsphere:
    # 是否打印sql
    props:
      sql:
        show: true
    datasource:
      names: ds0
      ds0:
        password: 'root123@'
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/customer_user
    rules:
      sharding:
        tables:
          customer_user:
            table-strategy:
              inline:
                algorithm-expression: customer_user$->{id % 2}
                sharding-column: id
            key-generator-column-name: id
            actual-data-nodes: ds{0}.customer_user$->{0..2}
