
spring:
  application:
    name: customer-user
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  shardingsphere:
    # 是否打印sql
    props:
      sql:
        show: true
    datasource:
      ds:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/customer_user?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        password: 'root123@'
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      names: ds
    sharding:
      binding-tables: customer_user
      tables:
        customer_user:
          actual-data-nodes: ds.customer_user_$->{0..2}
          key-generator:
            column: id
#            props:
#              worker:
#                id: 123
            type: SNOWFLAKE
          table-strategy:
            inline:
              algorithm-expression: customer_user_$->{id % 3}
              sharding-column: id